# whitelist
branches:
  only:
    - master
    - develop
    - /feature\/\w+/
language: swift
osx_image: xcode9.4
script:
    - xcodebuild clean test -project SmartBusinessCard.xcodeproj -scheme SmartBusinessCard -destination "platform=iOS Simulator,name=iPhone 7,OS=11.4" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
after_success: jazzy --min-acl private
